const services = [
  {
    title: "Switzerland – 7 Days in Zurich, Zermatt",
    img: "https://i.ibb.co/16LCWPh/services-1.jpg",
    rating: 4,
    desc: "Zermatt, town, Valais canton, southern Switzerland. It lies at the head of the Mattervisp Valley and at the foot of the Matterhorn",
    price: "3500",
    days: "7 Days",
    Availability: "Jan 16’ - Dec 16’",
    depart: "San Francisco",
    land: "Zurich",
    MinAge: "9+",
    MaxPeople: "34",
    TourDetail: `Switzerland is one of the stunning places on earth. With a high quality of life, gorgeous mountain views, and clear lakes, and modern amenities, the Swiss landscape will surely win you over. In this best Switzerland Itinerary 7 days, we will discover some of the most beautiful places to explore in 7 days in Switzerland.Area wise Switzerland is not huge, it’s like 4 times smaller than the size of Michigan in the US. And a smart way to explore Switzerland in 7 days is to keep 1 or 2 cities as your base and then venture out to the countryside with day trips. That will also help to keep accommodation costs low as you save on multiple night stays, stock up on groceries, and take public transportation to explore.This one week in Switzerland itinerary can be done without a car as well. We hope you enjoy these handpicked beautiful places in Switzerland for your itinerary.`,
    Destination: "Switzerland Zurich, Zermatt",
    DressCode: "sports jackets and trousers ",
    TourPlan1: `Switzerland is an expensive place to travel to and stay for the long term. If you budget things well, stay in a mid-range hotel with access to trams and trains (use public transportation), you can explore the country within affordable means.Switzerland has a very high standard of living, amazing landscape (which is free to view), and safety while traveling in the country makes up for the high price tag that comes with vacationing here. Come to think of it – all expensive cities/countries have a high living standard, clean public spaces (including toilets), less crime, and good infrastructure`,
    TourPlan2: `In Zurich, you cannot miss the Altstadt, which is the historic old town. Spend most of your time in Zurich by exploring iconic landmarks such as the Grossmünster Church and the Münsterbrücke and the Fraumünster church.`,
    TourPlan3: `Geneva is one of the most beautiful cities in Europe, and absolutely worth a stop during your trip throughout Switzerland. Located between three picturesque mountain ranges and beautiful Lake Geneva, the city is an outdoor playground. Walk around and get lost in its many beautiful green spaces and parks, and don’t miss the infamous flower clock made up of thousands of live flowers.`,
    pic1: "https://i.ibb.co/6P2tF4Y/Switzerland-1.jpg",
    pic2: "https://i.ibb.co/xSZtd0k/Switzerland-2.jpg",
    pic3: "https://i.ibb.co/zGGtTG5/Switzerland-3.jpg",
  },
  {
    title: "Dubai – All Stunning Place",
    img: "https://i.ibb.co/Q88TC6P/services-2.jpg",
    rating: 4,
    desc: "Located in the eastern part of the Arabian Peninsula on the coast of the Persian Gulf, Dubai aims to be the business hub of Western Asia.",
    price: "1200",
    days: "8 Hours",
    Availability: "Jan 16’ - Dec 16’",
    depart: "Dubai",
    land: "Dubai",
    MinAge: "11+",
    MaxPeople: "40",
    TourDetail: `This city of high-rises and shopping malls has transformed itself from a desert outpost to a destination du-jour, where tourists flock for sales bargains, sunshine, and family fun. Dubai is famous for sightseeing attractions such as the Burj Khalifa the world's tallest building and shopping malls that come complete with mammoth aquariums and indoor ski slopes. But this city has many cultural highlights and things to do, as well as all the glamorous modern add-ons. Take a wander around the Al Fahidi quarter, and you'll discover the Dubai of old, then cruise along Dubai Creek in a traditional dhow, and you'll soon realize there's more to this city than its flashy veneer`,
    Destination: "Dubai",
    DressCode: "Casual, comfortable and light",
    TourPlan1: `See the Sights: Dubai City Half Day Private Sightseeing Tour is one of the most convenient ways to see the city's sights. This guided tour takes you to the main attractions, including Jumeirah Mosque, Dubai Museum, Deira Gold Souq, and more.`,
    TourPlan2: `Head to the Desert: The Dubai Desert 4x4 Safari takes you on a desert adventure and includes a camel ride, sandboarding lessons, a sunset barbecue, and a belly dancing show.`,
    TourPlan3: `Soar over the City: Helicopter Flight over Dubai offers incredible views across the city and desert surroundings on a 15-minute or 25-minute helicopter ride. There is no better way to see the famous Palm Jumeirah or the manmade archipelago created in the shape of a world map, known as The World, than from the air.`,
    pic1: "https://i.ibb.co/mz4HpK9/dubai1.jpg",
    pic2: "https://i.ibb.co/5F9mS55/dubai2.jpg",
    pic3: "https://i.ibb.co/48R8MJ8/dubai3.jpg",
  },
  {
    title: "Italy – 6 Days",
    img: "https://i.ibb.co/Fq4jLXw/services-3.jpg",
    rating: 4,
    desc: "Italy is located in the center of the Mediterranean Sea, in Southern Europe,and is also considered part of Western Europe",
    price: "2000",
    days: "5 Days",
    Availability: "Jan 16’ - Dec 16’",
    depart: "San Francisco",
    land: "Rome",
    MinAge: "9+",
    MaxPeople: " 28",
    TourDetail: `You're in for a bellissimo journey through the spectacular cities of Italy, which kicks off in the 'Eternal City' of Rome. Join your travel companions and Travel Director for a memorable Welcome Reception. Your introduction to la dolce vita begins with an orientation drive past Rome's most magnificent sights.We embark on a very special included Dive Into Culture sightseeing tour with our Local Specialist at the Vatican this morning. Skip the queue and wander through its Museums and the Sistine Chapel, admiring the artistry of great masters and walking in the footsteps of popes who have found peace within its beautiful green landscapes for centuries.`,
    Destination: "Italy",
    DressCode: "Casual, comfortable and light",
    TourPlan1: `Visit the Sistine Chapel and St. Peter's Basilica in Rome, the Villa Barberini Gardens in Castel Gandolfo, the Basilica of St. Francis in Assisi and a glassblowing factory in Venice`,
    TourPlan2: `Rome, Florence and Venice are the stars of the show on the most incredible of Italy trips. This unforgettable trio features visits to food markets, ancient Roman ruins and the artistry of great masters. But that’s not all, as you’ll also get to dine with an Italian family in their beautiful Tuscan villa.`,
    TourPlan3: `View the Colosseum and Forum in Rome, Santa Croce Basilica and the Duomo in Florence, the Leaning Tower of Pisa and St. Mark's Basilica in Venice Explore Rome, Assisi, Florence, Pisa, Bologna and Venice with a Local Specialist`,
    pic1: "https://i.ibb.co/XX4G3z8/italy1.jpg",
    pic2: "https://i.ibb.co/bBFmY3s/italy2.jpg",
    pic3: "https://i.ibb.co/FnZTmBQ/italy3.jpg",
  },
  {
    title: "America – 2 Days in Lake Tahoe",
    img: "https://i.ibb.co/sWgkFZp/services-4.jpg",
    rating: 2,
    desc: "Lake Tahoe is a large freshwater lake in the Sierra Nevada of the United States.It straddles the state line between California and Nevada, west of Carson City. ",
    price: "300",
    days: "2 Days",
    Availability: "Jan 16’ - Dec 16’",
    depart: "San Francisco",
    land: "Lake Tahoe",
    MinAge: "9+",
    MaxPeople: "20",
    TourDetail: `Located 1,897 meters atop the majestic Sierra Nevada mountain range on the California and Nevada border, Lake Tahoe is widely considered one of the most beautiful places in the world. This natural treasure offers the ultimate high-country experience with superb outdoor recreation and magnificent scenery throughout the year.`,
    Destination: "Lake Tahoe",
    DressCode: "Casual, comfortable and light",
    TourPlan1: `Discover a hidden castle, Vikingsholm, on the edge of Emerald Bay. To get there, it’s about a 1.6-kilometer hike down a well-traveled path at about 1,900 meters. Along the way, enjoy amazing views of the bay and forest below, then take a tour of the 19th century estate. After your hike and tour, take in views of Lower Eagle Falls or unwind at Emerald Bay Beach.`,
    TourPlan2: `Discover a hidden castle, Vikingsholm, on the edge of Emerald Bay. To get there, it’s about a 1.6-kilometer hike down a well-traveled path at about 1,900 meters. Along the way, enjoy amazing views of the bay and forest below, then take a tour of the 19th century estate. After your hike and tour, take in views of Lower Eagle Falls or unwind at Emerald Bay Beach.`,
    TourPlan3: `Catch a paddlewheel boat cruise around Emerald Bay on a well-appointed ship straight out of the early 1900s. For a few hours you’ll be treated to great dining, signature cocktails and views you’ll have plenty of time to take in. South Lake Tahoe’s Heavenly Village is the place to pick up Lake Tahoe souvenirs and Sierra-style fashions, but you can also score lunch or dinner, go ice skating and see a movie. Elsewhere in the area, you can hop over to Stateline, Nevada for some grown-up gaming and entertainment.`,
    pic1: "https://i.ibb.co/vVWzqTX/lake1.jpg",
    pic2: "https://i.ibb.co/BTN8NLL/lake2.jpg",
    pic3: "https://i.ibb.co/7rbJLp9/lake3.jpg",
  },
  {
    title: "Japan – 5 Days in Tokyo, Fujikawa",
    img: "https://i.ibb.co/J3Xf9bB/services-5.jpg",
    rating: 3,
    desc: "Fujikawa was a town located in Ihara District, Shizuoka Prefecture, Japan Fujikawa was merged into the expanded city of Fuji.",
    price: "1600",
    days: "5 Days",
    Availability: "Jan 16’ - Dec 16’",
    depart: "San Francisco",
    land: "Fujikawa",
    MinAge: "9+",
    MaxPeople: "20",
    TourDetail: `Fujikawa Bridge View with Mount Fuji and Shinkansen Fujikawa Bridge Area Mt. Fuji Category Nature / scenery Educational tour Basic Information Access The Fujikawa Bridge stretches across the mouth of the Fuji River. This is the bridge the Shinkansen bullet train passes through. The bridge is famous as a great place to view Mount Fuji from. If you want to see the bridge, the shinkansen and Mount Fuji all together, you can go to the Fuji River riverbed for an amazing view.`,
    Destination: "Fujikawa",
    DressCode: "Casual, comfortable and light",
    TourPlan1: `There is also a park , on top of a hill, it's preferable to travel by car. Be frank, it is probably not special at all except in the cherry blossom season, so we visited the park during the cherry blossom festival , the time when cherry trees were in full bloom!When approaching the park by car slowly, waiting for the entry, I heard the song "Sakura" by was being broadcast. Songs after that were all Sakura related. It helped me well prepare a good mood for cherry blossom! Once we entered the park, we saw lots of cherry blossom trees surrounding the center, that many stalls were setup for snacks and goods
`,
    TourPlan2: `three festivals are awarded the title for factors such as its historical depth and its large-scale fireworks displays. Pick any one of these three (or all three!) to go to this summer, and you will fall in love with Japan’s summer skies.`,
    TourPlan3: `Tokyo Tower has been cherished by all of Japan as a symbol of the capital, and the country's tallest structure. Although its status of being Japan's tallest building has been passed onto the newer Tokyo SkyTree, Tokyo Tower is a still landmark that attracts many tourists from both within and beyond Japan's borders`,
    pic1: "https://i.ibb.co/myj3gMv/japan1.jpg",
    pic2: "https://i.ibb.co/4TC46gZ/Japan2.jpg",
    pic3: "https://i.ibb.co/dQq47pM/Japan3.jpg",
  },
  {
    title: "Finland – Helsinki, Santa Claus Town",
    img: "https://i.ibb.co/Z1bvgzk/services-6.jpg",
    rating: 4,
    desc: "Santa Claus Village is located in Lapland in Finland, only 8 km north of the Rovaniemi City Center. The destination is easily spotted with its towers and grand gateway.",
    price: "3500",
    days: "8 Days 7 Nights",
    Availability: "Jan 16’ - Dec 16’",
    depart: "San Francisco",
    land: "Santa Claus Town",
    MinAge: "9+",
    MaxPeople: "20",
    TourDetail: `In summer, Santa’s Igloos Arctic Circle let you experience Lapland’s unusual white light. In winter, in the same place, be amazed by the colorful show of northern lights that dance through the glass roof.The cabins of Santa Claus Holiday Village offer you the softest beds to land on after a day-well-spend. Santa Claus Holiday Village is open year-round. In summer 2018, new accommodation, Hotel Santa Claus Village, was opened just behind Holiday Village’s cottages.`,
    Destination: "Fujikawa",
    DressCode: "Casual, comfortable and light",
    TourPlan1: `In Arctic Circle Husky Park you can try husky sled rides in winter and visit the husky park in summer. Bearhill Husky’s dogs are in Santa Claus Village in winter, but in summer you can book company’s Kennel Tour.Reindeer you can find from Santa Claus Reindeer, where you can have rides of various lengths. In addition, you can accomplish a Reindeer Driving Licence. In summer, when the reindeer cannot pull a sled on snowless ground, you can meet and feed the animals.`,
    TourPlan2: `Snowman World is – naturally – a whole world made of snow. Experience adventures with snowman characters, admire ice sculptures in art gallery, and enjoy a drink in an ice bar. To give your experience a little bit of something, enjoy dinner in an Ice Restaurant.`,
    TourPlan3: `In the traditional rustic atmosphere in the Arctic Circle, north side of Santa Claus Village, lives sheep, goat, alpacas, reindeer, rabbits, hens and rooster. You can familiarize with domestic animals in their daily activities in Arctic weather conditions. In winter time, Elf’s Farm Yard offers an opportunity to cross the Arctic Circle with traditional Lappish wooden skis. All needed equipments are provided. Have a little picnic by campfire and enjoy safe ride down on snowy slide hill!`,
    pic1: "https://i.ibb.co/b7RM3Sg/finland1.jpg",
    pic2: "https://i.ibb.co/f1v71Rb/finland2.jpg",
    pic3: "https://i.ibb.co/CBcGjgr/finland3.jpg",
  },
];
